#!/bin/bash

# Read existing DNS servers from /etc/resolv.conf
dns_servers=$(grep "nameserver" /etc/resolv.conf | awk '{print $2}')

echo "Current DNS servers:"
echo "$dns_servers"

read -p "Do you want to replace the DNS servers? (yes/no): " replace_dns

if [ "$replace_dns" == "yes" ]; then
    echo "Choose a DNS server option:"
    echo "1) Google DNS"
    echo "2) CloudFlare DNS"
    echo "3) OpenDNS"
    echo "4) Special DNS"
    read -p "Enter your choice (1/2/3/4): " dns_choice

    case $dns_choice in
        1)
            new_dns="8.8.8.8 8.8.4.4"
            ;;
        2)
            new_dns="1.1.1.1 1.0.0.1"
            ;;
        3)
            new_dns="208.67.222.222 208.67.220.220"
            ;;
        4)
            read -p "Enter the custom DNS server: " custom_dns
            new_dns="$custom_dns"
            ;;
        *)
            echo "Invalid choice!"
            exit 1
            ;;
    esac

    # Update /etc/resolv.conf with new DNS servers
    echo "Updating /etc/resolv.conf..."
    echo "# Generated by DNS configuration script" > /etc/resolv.conf
    echo "nameserver $new_dns" >> /etc/resolv.conf

    echo "New DNS servers set:"
    cat /etc/resolv.conf

    # Test DNS server connectivity
    echo "Testing DNS server connectivity..."
    for server in $new_dns; do
        ping -c 3 "$server"
    done
else
    echo "DNS servers will not be changed."
fi
